openapi: 3.0.0
info:
  title: Chimoney Demo API
  version: 1.0.0
  description: |
    Portfolio demo – three basic endpoints for Chimoney:
      • Check Wallet Balance  
      • Send Money  
      • Get Transaction Status
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: https://api.chimoney.io/v1

tags:
  - name: Wallet
    description: Operations that read or modify a user wallet
  - name: Payments
    description: Endpoints for sending or receiving funds
  - name: Transactions
    description: Retrieve the status of previously created transactions

#
# ----------------------------------------------------------------------
# SECURITY (global – applies to every operation)
# ----------------------------------------------------------------------
#
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY

security:
  - ApiKeyAuth: []

#
# ----------------------------------------------------------------------
# PATHS
# ----------------------------------------------------------------------
#
paths:

  /wallet/balance:
    get:
      tags: [Wallet]
      summary: Check wallet balance
      description: Returns the current balance of the authenticated wallet.
      operationId: getWalletBalance
      responses:
        '200':
          description: Wallet balance retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  balance:
                    type: number
                    example: 125.75
                  currency:
                    type: string
                    example: USD
        '401':
          description: Invalid or missing API key
        '500':
          description: Unexpected server error

  /payments/send:
    post:
      tags: [Payments]
      summary: Send money
      description: Sends a payment to a recipient.
      operationId: sendPayment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [amount, currency, recipient]
              properties:
                amount:
                  type: number
                  example: 50
                currency:
                  type: string
                  example: USD
                recipient:
                  type: string
                  description: Email, phone, or unique user identifier
                  example: user@example.com
                reference:
                  type: string
                  description: Client-supplied reference for tracking
                  example: INV-2025-0001
            examples:
              emailRecipient:
                summary: Send to email
                value:
                  amount: 50
                  currency: USD
                  recipient: user@example.com
                  reference: INV-2025-0001
      responses:
        '200':
          description: Payment accepted
          content:
            application/json:
              schema:
                type: object
                properties:
                  transactionId:
                    type: string
                    example: tx_9a32bd1f
                  status:
                    type: string
                    example: pending
                  amount:
                    type: number
                    example: 50
                  currency:
                    type: string
                    example: USD
        '400':
          description: Validation error (missing or invalid fields)
        '401':
          description: Invalid or missing API key
        '500':
          description: Unexpected server error

  /transactions/{id}:
    get:
      tags: [Transactions]
      summary: Get transaction status
      description: Retrieves the status and details of a transaction by ID.
      operationId: getTransactionStatus
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Transaction ID returned from **Send money**
          example: tx_9a32bd1f
      responses:
        '200':
          description: Transaction found
          content:
            application/json:
              schema:
                type: object
                properties:
                  transactionId:
                    type: string
                    example: tx_9a32bd1f
                  status:
                    type: string
                    example: completed
                  amount:
                    type: number
                    example: 50
                  currency:
                    type: string
                    example: USD
                  createdAt:
                    type: string
                    format: date-time
                    example: 2025-08-19T12:00:00Z
        '401':
          description: Invalid or missing API key
        '404':
          description: Transaction not found
        '500':
          description: Unexpected server error
