// sidebars.js
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
module.exports = {
  /* ───────── 1) About Me ───────── */
  profileSidebar: [
    { type: 'doc', id: 'intro', label: 'About Me' },
  ],

  /* ───────── 2) Tooling docs you wrote by hand ───────── */
  toolingSidebar: [
    { type: 'doc', id: 'documentation-tooling/README',          label: 'README' },
    { type: 'doc', id: 'documentation-tooling/intro',           label: 'Introduction' },
    { type: 'doc', id: 'documentation-tooling/getting-started', label: 'Getting Started' },
    {
      type:  'category',
      label: 'API Reference (manual)',
      items: [{ type: 'autogenerated', dirName: 'documentation-tooling/api-reference' }],
    },
  ],

  /* ───────── 3) Chimoney API (README + auto-generated endpoints) ───────── */
  apiSidebar: [
    { type: 'doc', id: 'api-documentation/introduction',  label: 'Introduction' },
  
{
      type:  'category',
      label: 'Chimoney API Docs',
      items: [{ type: 'doc', id: 'api-documentation/getting-started',  label: 'Getting Started' },
        'api-documentation/reference/chimoney/get-wallet-balance', 'api-documentation/reference/chimoney/get-transaction-status','api-documentation/reference/chimoney/send-payment'],
    },

    /* autogenerated children will appear **after the first reload** */
  ],
};
