// sidebars.js
// Documentation: https://docusaurus.io/docs/api/sidebar

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
module.exports = {
  /* ────────────────────────────────
     1) “About Me”  (single page)
  ──────────────────────────────── */
  profileSidebar: [
    { type: 'doc', id: 'intro', label: 'About Me' },
  ],

  /* ────────────────────────────────
     2) “Project / Tooling” (manual docs you wrote)
  ──────────────────────────────── */
  toolingSidebar: [
    { type: 'doc', id: 'documentation-tooling/README',          label: 'README'          },
    { type: 'doc', id: 'documentation-tooling/intro',           label: 'Introduction'    },
    { type: 'doc', id: 'documentation-tooling/getting-started', label: 'Getting Started' },
    {
      type:  'category',
      label: 'API Reference (manual examples)',
      items: [
        { type: 'autogenerated', dirName: 'documentation-tooling/api-reference' },
      ],
    },
  ],

  /* ────────────────────────────────
     3) “Chimoney API” (100 % generated by the
        docusaurus-plugin-openapi-docs plugin)
        ⚠️  Do NOT place any files manually under
        docs/api-documentation/reference – the plugin
        owns that folder.
  ──────────────────────────────── */
 

  apiSidebar: [
    {
       type:  'category',
      label: 'API Reference',
      items: [
        { type: 'autogenerated', dirName: 'api-documentation' },],
    },
  ],
};
