// sidebars.js
module.exports = {
  profileSidebar: [
    { type: 'doc', id: 'intro', label: 'About Me' },
  ],
  toolingSidebar: [
    { type: 'doc', id: 'documentation-tooling/README', label: 'README' },
    { type: 'doc', id: 'documentation-tooling/intro', label: 'Introduction' },
    { type: 'doc', id: 'documentation-tooling/getting-started', label: 'Getting Started' },
    {
      type: 'category',
      label: 'API Reference',
      items: [{ type: 'autogenerated', dirName: 'documentation-tooling/api-reference' }],
    },
  ],
};
